### ISSUE TITLE
dist file is old

### ISSUE THREAD

**Issue by alexilyaev** [frapontillo/angular-highcharts#1]
@frapontillo Hey there, I see the file under `dist` folder is outdated.
Can we have a new release?

Also, the build adds up the Constants, is that necessary if I want only some other type of chart?

**Comment by frapontillo** [comment]
There's actually no release yet, as I feel like the package never reached a stable condition; sadly, I also can't currently keep it updated.
You can still reference and use all the files in the `src` directory.

**Comment by alexilyaev** [comment]
@frapontillo Yeah, that's what I did, and it worked, but I had to put it together and remove the extra parts, whereas the `dist` update could have been clean and concise.

Too bad, your repo looked the most promising among the `angular-highcharts` wrappers.
